# Generated by Django 5.0.3 on 2024-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0002_tbl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='vat_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='vat_rate',
            field=models.IntegerField(null=True),
        ),
    ]
