# Generated by Django 5.0.3 on 2024-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0004_tbl_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_weight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
