# Generated by Django 5.0.3 on 2024-04-03 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0005_tbl_product_product_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_product',
            old_name='vat_amount',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='tbl_product',
            old_name='vat_rate',
            new_name='tax_rate',
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='product_measure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_signup',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_signup',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_signup',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_signup',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_signup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='tbl_Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_country')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_signup')),
            ],
        ),
    ]
