# Generated by Django 5.0.3 on 2024-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0007_tbl_wishlist_quantity_tbl_wishlist_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_signup',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
