# Generated by Django 5.0.3 on 2024-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0010_remove_tbl_cart_created_at_remove_tbl_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='sub_total',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
