# Generated by Django 5.0.3 on 2024-04-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0012_tbl_billing_address_tbl_shipment_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_billing_address',
            old_name='apt_number',
            new_name='Eircode',
        ),
        migrations.RenameField(
            model_name='tbl_shipment_address',
            old_name='apt_number',
            new_name='Eircode',
        ),
        migrations.RemoveField(
            model_name='tbl_billing_address',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='tbl_shipment_address',
            name='zip_code',
        ),
    ]
