# Generated by Django 5.0.3 on 2024-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0013_rename_apt_number_tbl_billing_address_eircode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
