# Generated by Django 5.0.3 on 2024-04-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0014_alter_tbl_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_wishlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='tbl_wishlist',
            name='total_price',
        ),
        migrations.CreateModel(
            name='tbl_Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.CharField(max_length=100, null=True)),
                ('item_price', models.IntegerField(null=True)),
                ('ship_charge', models.IntegerField(null=True)),
                ('total_after_ship', models.IntegerField(null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_signup')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_checkout_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_checkout')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_signup')),
            ],
        ),
    ]
