# Generated by Django 5.0.3 on 2024-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0016_tbl_checkout_ship_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_checkout',
            name='ship_address',
        ),
        migrations.AddField(
            model_name='tbl_checkout',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
