# Generated by Django 5.0.3 on 2024-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0017_remove_tbl_checkout_ship_address_tbl_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_checkout',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
