# Generated by Django 5.0.3 on 2024-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0018_tbl_checkout_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_checkout',
            name='ship_charge',
            field=models.FloatField(null=True),
        ),
    ]
