# Generated by Django 5.0.3 on 2024-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0019_alter_tbl_checkout_ship_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_checkout',
            name='invoice_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_checkout',
            name='orderid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_checkout',
            name='total_after_ship',
            field=models.FloatField(null=True),
        ),
    ]
