# Generated by Django 5.0.3 on 2024-04-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0020_tbl_checkout_invoice_number_tbl_checkout_orderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_checkout',
            name='ship_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_shipment_address'),
        ),
    ]
