# Generated by Django 5.0.3 on 2024-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0021_tbl_checkout_ship_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_signup',
            name='dp',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
