# Generated by Django 5.0.3 on 2024-04-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0022_tbl_signup_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_category',
            name='status',
        ),
        migrations.AddField(
            model_name='tbl_category',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
