# Generated by Django 5.0.3 on 2024-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0023_remove_tbl_category_status_tbl_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_category',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
