# Generated by Django 5.0.3 on 2024-04-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0024_tbl_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='gross_total',
            field=models.IntegerField(null=True),
        ),
    ]
