# Generated by Django 5.0.3 on 2024-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0025_tbl_product_gross_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='gross_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
