# Generated by Django 5.0.3 on 2024-04-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0028_alter_tbl_product_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
