# Generated by Django 5.0.3 on 2024-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0029_tbl_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='best_score',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
