# Generated by Django 5.0.3 on 2024-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0030_tbl_product_best_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='sub_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
