# Generated by Django 5.0.3 on 2024-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0032_tbl_delivery_partner_tbl_order_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_delivery_partner',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
