# Generated by Django 5.0.3 on 2024-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0034_tbl_login_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order_assign',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
