# Generated by Django 5.0.3 on 2024-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0035_tbl_order_assign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_checkout',
            name='item_price',
            field=models.FloatField(null=True),
        ),
    ]
