# Generated by Django 5.0.3 on 2024-06-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0036_alter_tbl_checkout_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_price', models.FloatField(null=True)),
                ('deal_type', models.CharField(max_length=100, null=True)),
                ('deal_start_date', models.DateField(null=True)),
                ('deal_end_date', models.DateField(null=True)),
                ('deal_start_time', models.TimeField(null=True)),
                ('deal_end_time', models.TimeField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_product')),
            ],
        ),
    ]
