# Generated by Django 5.0.3 on 2024-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0039_tbl_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
