# Generated by Django 5.0.3 on 2024-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0040_tbl_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='our_price',
            field=models.FloatField(null=True),
        ),
    ]
