# Generated by Django 5.0.3 on 2024-06-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0041_tbl_product_our_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                       to='GoApp.tbl_checkout_products')),
                ('product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_product')),
            ],
        ),
    ]
