# Generated by Django 5.0.3 on 2024-06-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GoApp', '0042_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rating',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_signup'),
        ),
    ]
