# Generated by Django 5.0.3 on 2024-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0043_tbl_rating_status_tbl_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_checkout',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_checkout',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
