# Generated by Django 5.0.3 on 2024-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0045_tbl_admin_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_checkout',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
