# Generated by Django 5.0.3 on 2024-07-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0048_rename_our_price_tbl_product_o_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_signup',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
