# Generated by Django 5.0.3 on 2024-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0050_tbl_cart_products_deal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_poster1',
            name='link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_poster2',
            name='link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_poster3',
            name='link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_poster4',
            name='link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_poster5',
            name='link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_poster6',
            name='link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_poster7',
            name='link',
            field=models.IntegerField(null=True),
        ),
    ]
