# Generated by Django 5.0.3 on 2024-07-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoApp', '0051_tbl_poster1_link_tbl_poster2_link_tbl_poster3_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_poster1',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_poster2',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_poster3',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_poster4',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_poster5',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_poster6',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_poster7',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoApp.tbl_category'),
        ),
    ]
