from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index),
    path("Gomart_Admin/",views.Admin_login),
    path("login/check/",views.login_check),
    path("Admin_Home/",views.Admin_Home),
    path("country/",views.country),
    path("add_country/",views.add_country),
    path("brands/",views.brands),
    path("add_brands/",views.add_brands),
    path("category/",views.category),
    path("add_category/",views.add_category),
    path("products/",views.products),
    path("add_product/",views.add_product),
    path("show_by_country/<id>",views.show_by_country),
    path("show_by_brand/<id>",views.show_by_brand),
    path("shop_by_category/<id>",views.shop_by_category),
    path("logout_admin/",views.logout_admin),
    path("contact/",views.contact),
    path("Login/",views.Login,name="Login"),
    path("save_signup/",views.save_signup),
    path("check_email/",views.check_email),
    path("check_login/",views.check_login,name="check_login"),
    path("HomePage/",views.HomePage,name="HomePage"),
    path("add_to_wishlist/<id>",views.add_to_wishlist,name="add_to_wishlist"),
    path("add_vat_gst/",views.add_vat_gst,name="add_vat_gst"),
    path("view_product_single/<id>",views.view_product_single,name="view_product_single"),

    path("cart_user/",views.cart_user,name="cart_user"),

    path("wishlist/",views.wishlist,name="wishlist"),
    path("all_products/",views.all_products,name="all_products"),
    path("add_to_cart_products/<id>/<price>",views.add_to_cart_products,name="add_to_cart_products"),
    path("signup/",views.signup,name="signup"),
    path("shop_by_category_user/<id>",views.shop_by_category_user,name="shop_by_category_user"),
    path("signout_user/",views.signout_user,name="signout_user"),
    path("update_cart_products/",views.update_cart_products,name="update_cart_products"),
    path("update_cart_total/",views.update_cart_total,name="update_cart_total"),
    path("checkout/",views.checkout,name="checkout"),
    path("about/",views.about,name="about"),
    path("save_ship_address/",views.save_ship_address,name="save_ship_address"),
    path("save_bill_address/",views.save_bill_address,name="save_bill_address"),
    path("checkout1/<id>",views.checkout1,name="checkout1"),

    path("paymenthandler/",views.paymenthandler,name="paymenthandler"),
    path("all_products_user/",views.all_products_user,name="all_products_user"),
    path("my_account/",views.my_account,name="my_account"),
    path("remove_product/",views.remove_product,name="remove_product"),
    path("forgot_password/",views.forgot_password,name="forgot_password"),
    path("password_send/",views.password_send,name="password_send"),
    path("view_product_single_user/<id>",views.view_product_single_user,name="view_product_single_user"),
    path("remove_from_wishlist/<id>",views.remove_from_wishlist,name="remove_from_wishlist"),
    path("payment_success/<id>",views.payment_success,name="payment_success"),
    path("cod_invoice/",views.cod_invoice,name="cod_invoice"),
    path("cod_invoice_view/<id>",views.cod_invoice_view,name="cod_invoice_view"),
    path("pending_orders/",views.pending_orders,name="pending_orders"),
    path("view_check_products_invoice/<id>",views.view_check_products_invoice,name="view_check_products_invoice"),
    path("completed_orders/",views.completed_orders,name="completed_orders"),

    path("process_payment/",views.process_payment,name="process_payment"),
    path("view_check_products/<id>",views.view_check_products,name="view_check_products"),
    path("all_product_user_sort/",views.all_product_user_sort,name="all_product_user_sort"),
    path("update_profile/",views.update_profile,name="update_profile"),
    path("save_password/",views.save_password,name="save_password"),
    path("edit_products/<id>",views.edit_products,name="edit_products"),
    path("quick-enquiry/",views.quick_enquiry,name="quick_enquiry"),
    path("save_enquiry/",views.save_enquiry,name="save_enquiry")


]
